name: create-release
run-name: create-release
on:
  # for testing changes before merging
  push:
#  workflow_dispatch:
#    inputs:
#      version:
#        description: 'Version Number for the new release'
#        required: true
#      branch:
#        description: 'Branch to generate release from'
#        required: true
#        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: setup
        run: |
          git config --global user.email zhensler12@gmail.com
          git config --global user.name ${{ github.actor }}
      - name: build
        run: |
          docker buildx --platform linux/amd64,linux/arm64/v8 -t sous-chef-image -f Dockerfile .
          docker save sous-chef-image:latest | gzip > sous-chef-image_${{ inputs.version }}.tar.gz
#      - name: Create release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ github.ref_name }}
#        run: |
#          gh release create ${{ inputs.version }} sous-chef-image_${{ inputs.version }}.tar.gz