name: deploy
run-name: deploy
on:
  push:
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          git config --global user.email zhensler12@gmail.com
          git config --global user.name ${{ github.actor }}
      - name: build
        run: |
          docker build -t sous-chef-image -f Dockerfile .
          docker save sous-chef-image:latest | gzip > sous-chef-image_latest.tar.gz
      - name: deploy
        uses: actions/upload-artifact@v4
        with:
          name: v1.0
          path: sous-chef-image_latest.tar.gz