name: deploy
run-name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          git config --global user.email zhensler12@gmail.com
          git config --global user.name ${{ github.actor }}
      - name: build
        run: |
          makedir out
          docker build -o ./out -t sous-chef-image -f Dockerfile .
      - name: deploy
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: out